extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
plugins:
  - '@typescript-eslint'
  - 'googleappsscript'
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  tsconfigRootDir: __dirname,
root: true
env:
  browser: true
  'googleappsscript/googleappsscript': true
rules:
  eqeqeq: error
  strict: off
  '@typescript-eslint/no-unsafe-argument': off
  '@typescript-eslint/explicit-function-return-type': error
  '@typescript-eslint/no-explicit-any': error
